version: '3.3'
services:
    opencart:
        container_name: opencart_dev
        build: ./docker/opencart
        ports:
            - '8080:80'
            - '8081:443'
            - '3306:3306'
        restart: always

    nginx_proxy:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
            - '80:80'   # Public HTTP Port
            - '443:443' # Public HTTPS Port
            - '81:81'   # Admin Web Port
        environment:
            DB_MYSQL_HOST: "db"
            DB_MYSQL_PORT: 3306
            DB_MYSQL_USER: "npm"
            DB_MYSQL_PASSWORD: "npm"
            DB_MYSQL_NAME: "npm"
        volumes:
            - ./mnt/nginx_proxy/data:/data
            - ./mnt/nginx_proxy/letsencrypt:/etc/letsencrypt
        depends_on:
            - db

    db:
        image: 'jc21/mariadb-aria:latest'
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 'npm'
            MYSQL_DATABASE: 'npm'
            MYSQL_USER: 'npm'
            MYSQL_PASSWORD: 'npm'
        volumes:
            - ./mnt/mysql:/var/lib/mysql

    # Uncomment and modify the following section if you want to add FileBrowser
    # filebrowser:
    #     container_name: filebrowser
    #     ports:
    #         - '8082:80'  # Adjust the host port as needed
    #     volumes:
    #         - ./mnt/:/data
    #     environment:
    #         - FB_BASEURL=/f
    #     image: hurlenko/filebrowser:v2.23.0
    #     restart: always
